### ISSUE TITLE
Create databases interface(s)

### ISSUE THREAD

**Issue by bmsrangel** [bmsrangel/todo_bloc#3]
This app will initially use one database (SQLite). However, in the future it might use two, and the second one will have a table which doesn't exist in the local storage. So it may be convenient to create CRUD methods for the three tables according to the Hasura model and it'll be verified if this interface can be used by SQLite as well.

In short, create CRUD methods for:
* users table
* projects table
* tasks table

**Comment by noti0nS** [comment]
Why must have the users table? The Firebase will do it, right?

Actually the bigger problem is the user. Every table are same. If we removed the user, we can create an unique interface and implements it on database classes.

**Comment by bmsrangel** [comment]
> Why must have the users table? The Firebase will do it, right?

Because we want to store the id and the name (and maybe the phone, if that's the case). These data will not be stored in Firebase because we won't use the database tool, so they must be stored in Hasura.
