### ISSUE TITLE
UI Elements - Project Cards

### ISSUE THREAD

**Issue by bmsrangel** [bmsrangel/todo_bloc#7]
This app will contain a list of projects (which will contain a list of tasks each). So, a widget representing this cards will be necessary.

This widget will receive as parameter the project name and the list of tasks of the project. Then, it will show the project name and tasks status by counting the number of completed tasks and the total tasks number. It will also show the first task not completed.

There will be an indication to the selected card. It's possible to try an Elevation from the Card widget, but if it's not possible to change the shadow color, it may be necessary to use a Container with a shadow decoration.

If the elevation/shadow is not good enough, another solution can be implemented (such as border color changing or bottom border indications).

![Card 1](https://user-images.githubusercontent.com/39227201/89124733-aa50aa80-d4af-11ea-8c0d-be929569de3a.png)

**Comment by noti0nS** [comment]
I think changes the size and increase the shadow (with a little blur) is good.
